service: php-jquery-sqlite-starter-pack
image: ashleyrudland87/php-jquery-sqlite-starter-pack

servers:
  web:
    hosts:
      - <%= ENV["VPS_IP_ADDRESS"] %>

builder:
  arch: amd64
  
env:
  clear:
    IS_PROD: "y"
    PHP_ERROR_REPORTING: "32767"
    PHP_DISPLAY_ERRORS: "0"
    PHP_LOG_ERRORS: "1"
    SQLITE_WEB_PASSWORD: <%= ENV['SQLITE_WEB_PASSWORD'] %>

volumes:
  - /data:/data

registry:
  username:
    - DOCKER_USERNAME
  password:
    - DOCKER_PASSWORD

healthcheck:
  path: /api/up
  port: 80