service: php-jquery-sqlite-starter-pack
image: ashleyrudland87/php-jquery-sqlite-starter-pack

servers:
  web:
    hosts:
      - <%= ENV["VPS_IP_ADDRESS"] %>

env:
  clear:
    IS_PROD: "y"
    PHP_ERROR_REPORTING: "32767"
    PHP_DISPLAY_ERRORS: "0"
    PHP_LOG_ERRORS: "1"

volumes:
  - /data:/data

registry:
  username:
    - DOCKER_USERNAME
  password:
    - DOCKER_PASSWORD

healthcheck:
  path: /
  port: 80
  interval: 10s
  timeout: 30s
  retries: 3

ports:
  - 80:80